### ISSUE TITLE
Where is the RenderPasses/ReSTIR folder?

### ISSUE THREAD

**Issue by StringWeaver** [Alegruz/Screen-Space-ReSTIR-GI#1]
Hello, in README there is an introduction said:

>  Add the passes(`ReSTIR` and `ReSTIRGIBuffer` folders) in `RenderPasses` into `Falcor/Source/RenderPasses` directory so that you have a `Falcor/Source/RenderPasses/ReSTIRGI` and `Falcor/Source/RenderPasses/ReSTIRGIGBuffer` directories

But I can only find `ReSTIRGIGBuffer` in `RenderPasses`, I guess maybe you forget to put it in, so I put this issue as a reminder, hope this don't borther you.

**Comment by Alegruz** [comment]
Just pushed a commit with the folder

Thank you for the reminder!

**Comment by StringWeaver** [comment]
Hi, thank you very much for the commit! I tested it today and found that the `GlobalIlluminationPass` in the render garph of `ReSTIRGIPassWithGBuffer.py` is not contained in the falcor source code, could you please upload that code too? Very sorry to bother you again.

**Comment by Homuri-hkr** [comment]
Hi @Alegruz  as I try to load it for testing I also got notice that `GlobalIlluminationPass` is missing. 

Output shows as follows:

```
(Info) Enabling the D3D12 debug layer
(Info) Successfully created device with feature level: D3D_FEATURE_LEVEL_12_2
(Warning) Can't load render-pass library 'C:\Falcor\Falcor-5.1\Bin\x64\Debug\GlobalIlluminationPass.dll'. File not found.
(Info) Can't find a render-pass named 'GlobalIlluminationPass'. Trying to load a render-pass library 'GlobalIlluminationPass.dll'.
(Warning) Can't load render-pass library 'C:\Falcor\Falcor-5.1\Bin\x64\Debug\GlobalIlluminationPass.dll'. File not found.
(Warning) Trying to create a render-pass named 'GlobalIlluminationPass', but no such type exists in the library.
(Error) Error when loading configuration file: C:\Falcor\Falcor-5.1\Source\Mogwai\Data\ReSTIRGIPassWithGBuffer.py
RuntimeError: Can't create a render pass named 'GlobalIlluminationPass'. Make sure the required DLL was loaded.

At:
  <string>(26): render_graph_ReSTIRGI
  <string>(71): <module>
```

It would be great if you could upload this pass as well.
Thanks!

**Comment by Alegruz** [comment]
@Cook21 @Homuri-hkr Just pushed a commit that includes GI pass

**Comment by Homuri-hkr** [comment]
> 

It worked for me. Thanks!

**Comment by StringWeaver** [comment]
Unfortunately I can't get it work properly, I did following steps:

1. Pull latest falcor code
1. Copy those 3 render passes into RenderPasses folder.
1. In Visual Studio, for each of these 3 render pass, right click RenderPasses folder and click `"add"-"Existing Project"`, then select corresponding `.vcxproj` file
1. Copy `ReSTIRGI` folder into Rendering folder
1. In Visual Studio, create a filter called `ReSTIRGI` under Falcor/Rendering, click `"add"-"Existing item"`, then select all files under `ReSTIRGI` folder

But under DebugD3D12 configuration, after the scene is loaded, it will emit these error and crash:
```
D3D12 ERROR: ID3D12CommandList::ClearUnorderedAccessViewUint: ClearUnorderedAccessView* methods are not compatible with Structured Buffers. StructuredByteStride is set to 24 for resource 0x0000028526C1EE20:'Unnamed ID3D12Resource Object'. [ RESOURCE_MANIPULATION ERROR #1156: CLEARUNORDEREDACCESSVIEW_INCOMPATIBLE_WITH_STRUCTURED_BUFFERS]
Debug Error!

Program: E:\code\Falcor\Bin\x64\Debug\Mogwai.exe

HEAP CORRUPTION DETECTED: after Normal block (#28394299) at 0x00000285AD959D50.
CRT detected that the application wrote to memory after end of heap buffer.
```
Under ReleaseD3D12 configuration, it can run successfully but rendering result is incorrect:
![release.jpg](https://cdn.nlark.com/yuque/0/2022/jpeg/1314132/1659012251258-d3179727-dfa0-450d-a5f8-ea4e28bbe556.jpeg#clientId=u8ce037e1-b008-4&crop=0&crop=0&crop=1&crop=1&from=ui&id=u6c170e82&margin=%5Bobject%20Object%5D&name=release.jpg&originHeight=832&originWidth=1392&originalType=binary&ratio=1&rotation=0&showTitle=true&size=223414&status=done&style=none&taskId=ue77e9fb7-5ab6-4b11-a564-cf6dda3d768&title=VeachAjar.pyscene "VeachAjar.pyscene")

@Homuri-hkr @Alegruz please help me with this, I will appreciate it!

**Comment by Alegruz** [comment]
@Cook21 I would advise you to use the same version (5.1) that I've used

**Comment by StringWeaver** [comment]
@Alegruz Yes I am using falcor version 5.1, currently it is the latest version

**Comment by Alegruz** [comment]
Is that the scene from the ReSTIR PT project?
if so, that's how it worked out for me too

@Cook21 
Might be a bug, but unfortunately, I have no time to investigate

Sorry ;(

**Comment by StringWeaver** [comment]
Yes it is the same scene.
I totally understand that you don’t have extra time to investigate this, it is fine cause you’ve already done a lot. I will look into it.

**Comment by HyperMn** [comment]
@Cook21 Hi dude, recently I also meet the same problem. And I guess the problem is happening due to incorrectly reset mpFinalShading in ``ReSTIRGIPass.cpp``. Did you fix this problem? Hope to get your any reply :)

**Comment by StringWeaver** [comment]
@HyperMn Unfortunately no, I olny know that this error happens at ReSTIRGIPass.cpp line 362:
```
mpFinalShading->setVars(nullptr);
```

**Comment by HyperMn** [comment]
@Cook21 Thanks for replying! I will continue to work on it.
