### ISSUE TITLE
Confusion on creating multiple ScreenSpaceReSTIR instances

### ISSUE THREAD

**Issue by HyperMn** [Alegruz/Screen-Space-ReSTIR-GI#2]
Sorry to bother you. I have the same problem with Cook21 in another issue. 
I find it is because mpFinalShading has a writing out of bounds problem, and when calling mpFInalShading->setVars(nullptr) or just set mpFinalShading = nullptr, Falcor will give a runtime Error. ``ReSTIRGIPass.cpp``
When I check the problem more detailly, I'm confused on why create a mpScreenSpaceReSTIR array, and what is the role of variable ``mRequestParentRecompile``, it seems to be a variable to make mpFinalShading recompile, but im not sure.
Can you please take some time to give a answer? Any reply is appreciated.

**Comment by HyperMn** [comment]
I found the code I asked before is wrote by Daqi Lin, so I believe that's no problem(hope so).
And when you comment ``//var["ReSTIRInstanceID"] = instanceID;`` in ReSTIRGI.cpp(about in 442 line), there is no warning anymore. So I guess the memory problem happens here, but the rendering result still is not correct:(

**Comment by HyperMn** [comment]
Finally I found just replacing ``//var["ReSTIRInstanceID"] = instanceID;`` by ``//var["ReSTIRInstanceID"] = (uint_32)instanceID;``, the problem would be solved...
Originally, instanceID is the type of ``size_t``, there are some bit byte alignment problems happening during the data passing I guess.

**Comment by StringWeaver** [comment]
@HyperMn Did you get the correct rendering result? I tried your fix and there is still no indirect lighting...

**Comment by HyperMn** [comment]
@Cook21 Not yet;( I am still working on it currently.
